export default [
  "Have you been promoted?",
  "Have you left your current job?",
  "Have you changed the hours you work?",
  "Have you changed your job role within the organisation",
  "Are you currently looking for a job?",
  "Are you no longer interested in being in employment?",
  "Have you started a new job in a new organisation?",

  "The people I work with have excellent knowledge of autism",
  "I feel that if a new person was to join the team and they disclosed they were autistic, they would be well supported and understood by others",
  "I feel that the management of the team are constantly improving their knowledge about autism",
  "It is easy to find information within the organisation about supporting autistic employees",
  "There are established pathways for autistic people to seek advice and support for managing their daily work activities",
  "The organisation has been proactive in making adjustments and providing autism awareness training for employees",
  "I think the organisation performs better than other organisations in the sector in terms of quality of support for autistic employees",

  "Thinking about your most recent work experience, how confident are you in your ability to: Know what is expected of you as a worker",
  "Thinking about your most recent work experience, how confident are you in your ability to: Help build a team as a working unit",
  "Thinking about your most recent work experience, how confident are you in your ability to: Determine what is expected of you on the job",
  "Thinking about your most recent work experience, how confident are you in your ability to: Know how things \"really work\" inside an organisation",
  "Thinking about your most recent work experience, how confident are you in your ability to: Be clear with presenting your ideas",
  "Thinking about your most recent work experience, how confident are you in your ability to: Work under pressure",
  "Thinking about your most recent work experience, how confident are you in your ability to: Master an organisation's slang and special jargon",
  "Thinking about your most recent work experience, how confident are you in your ability to: Manage conflict among group members",
  "Thinking about your most recent work experience, how confident are you in your ability to: Understand what all of the duties of your role entail",
  "Thinking about your most recent work experience, how confident are you in your ability to: Solve new and difficult problems",
  "Thinking about your most recent work experience, how confident are you in your ability to: Work under extreme circumstances",
  "Thinking about your most recent work experience, how confident are you in your ability to: Understand the politics in the organisation",
  "Thinking about your most recent work experience, how confident are you in your ability to: Continue to learn once you're on the job",
  "Thinking about your most recent work experience, how confident are you in your ability to: Develop cooperative working relationships with others",
  "Thinking about your most recent work experience, how confident are you in your ability to: Invent new ways of doing things",
  "Thinking about your most recent work experience, how confident are you in your ability to: Solve most problems even though no solution is immediately apparent",
  "Thinking about your most recent work experience, how confident are you in your ability to: Find out exactly what a problem is when fist becoming aware of it",
  "Thinking about your most recent work experience, how confident are you in your ability to: Listen effectively to gain information",
  "Thinking about your most recent work experience, how confident are you in your ability to: Know an organisation's long-held traditions",
  "Thinking about your most recent work experience, how confident are you in your ability to: Work well in situations that other people consider stressful",
  "Thinking about your most recent work experience, how confident are you in your ability to: Understand the behaviour appropriate to your role",
  "Thinking about your most recent work experience, how confident are you in your ability to: Challenge things that are done by the book",
  "Thinking about your most recent work experience, how confident are you in your ability to: Learn from your mistakes",
  "Thinking about your most recent work experience, how confident are you in your ability to: Solve problems no matter how complex",
  "Thinking about your most recent work experience, how confident are you in your ability to: Coordinate tasks within you work group",
  "Thinking about your most recent work experience, how confident are you in your ability to: Learn to improve on your past performance",
  "Thinking about your most recent work experience, how confident are you in your ability to: Be sensitive to other's feelings and attitudes",
  "Thinking about your most recent work experience, how confident are you in your ability to: Function well at work even when faced with personal difficulties",
  "Thinking about your most recent work experience, how confident are you in your ability to: Concentrate on what someone is saying to you even though other things could distract you",
  "Thinking about your most recent work experience, how confident are you in your ability to: Listen effectively to understand opposing points of view",
  "Learning productively on the job",
  "Solving problems at work",
  "Accomplishing recent work well under time and schedule constraints",
  "Understanding what is expected of you in your current role",
  "Working effectively in a team environment",
  "Demonstrating sensitivity to others",
  "Recognising what the accepted practices are in your organisation",
  "Managing yourself well in the workplace" ];
